name: Deploy Angular App
on:
    workflow_call:
      inputs:
        username:
          description: 'A username passed from the caller workflow'
          default: 'john-doe'
          required: false
          type: string
jobs:
    print-username:
        runs-on: ubuntu-latest

    